name: Upload to S3 and invalidate CloudFront cache
on:
  push:
    branches:
      - master
jobs:
  run:
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    steps:
      - uses: actions/checkout@v1

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Install dependencies Using pnpm
        run: pnpm install

      - name: Build
        run: pnpm run build

      - name: S3 and CloudFront Deploy
        uses: lbertenasco/s3-deploy@v1.2.4
        with:
          folder: out
          bucket: ${{ secrets.AWS_S3_BUCKET_NAME }}
          dist-id: ${{ secrets.AWS_CLOUDFRONT_DISTRIBUTION_ID }}
          invalidation: /*